### ISSUE TITLE
Inventory does not find newly created servers

### ISSUE THREAD

**Issue by shadycuz** [sage905/cloudatcost-ansible-module#4]
So if you spin up a new server, it doesn't have a label so it is not found with the cac_inv.py 

What happens if I name 2 servers the same name? hmmm

I think we should be building server list by something unique like the vmname or servername. We can then display a label if it has one or a server name if it doesn't.

Also I tried to save a server with a labe "test-Mygroup-" and CAC strips the "-" out of the string!@!@!@!@.

So I will need to find another way =/

I will make the changes tomorrow for this and submit a PR.

Thanks,
Levi

**Comment by ptoal** [comment]
Hey,  Sorry I haven't been responsive.  I've been studying for my AWS Solution Architect Associate exam.

Feel free to tinker all you like, and submit PR's.  Just be aware that there are some limitations in the way that the CaC API functions.  Whatever you do, make sure you write tests, and then make sure that it works on the actual servers.

There are lots of little irritating things about the API that just don't allow you to idempotently perform actions.  Creating a server is an example.  It's supposed to create a task, but the task API doesn't work.  So I just poll the API to see if the server is created.  The caveat is that sometimes the server is created in the API listservers.php, but isn't actually created.  If you try to change something like the label at this point, the provisioning process goes haywire.

I look forward to any improvements you can make.  It was a bit frustrating writing this module, and I hope you have better luck with it. :)

**Comment by shadycuz** [comment]
Hey,

No problem. Good luck with the exam. I'll make what I can with the API. I'm
self taught, about time I learn about unit testing. I got some ideas for
turning out some devops automation with this module and ansible but I'll
have to learn ansible as I go.

Thanks,
Levi

On Mar 20, 2017 10:01 PM, "Patrick Toal" <notifications@github.com> wrote:

Hey, Sorry I haven't been responsive. I've been studying for my AWS
Solution Architect Associate exam.

Feel free to tinker all you like, and submit PR's. Just be aware that there
are some limitations in the way that the CaC API functions. Whatever you
do, make sure you write tests, and then make sure that it works on the
actual servers.

There are lots of little irritating things about the API that just don't
allow you to idempotently perform actions. Creating a server is an example.
It's supposed to create a task, but the task API doesn't work. So I just
poll the API to see if the server is created. The caveat is that sometimes
the server is created in the API listservers.php, but isn't actually
created. If you try to change something like the label at this point, the
provisioning process goes haywire.

I look forward to any improvements you can make. It was a bit frustrating
writing this module, and I hope you have better luck with it. :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sage905/cloudatcost-ansible-module/issues/4#issuecomment-287954127>,
or mute the thread
